name: Demo

on:
  workflow_dispatch:

jobs:
  job-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a long log (Example)
        run: |
          echo "Generating a simulated log..."
          echo " __      _(_)____   ___| (_)" >> log.txt
          echo " \\ \\ /\\ / / |_ /  / __| | |" >> log.txt
          echo "  \\ V  V /| |/ / | (__| | |" >> log.txt
          echo "   \\_/\\_/|_/___|  \\___|_|_|" >> log.txt
          echo "Scanning virtual machine image ami-abcdef123456789" >> log.txt
          echo "Vulnerable packages: CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0" >> log.txt
          echo "Scan was successfully performed and no vulnerabilities were detected" >> log.txt
          echo "Scan report: https://app.wiz.io/findings/example/12312454" >> log.txt
          echo "This is the noisy part" >> log.txt
          for i in {1..10000}; do echo "Noise $i"; done >> log.txt

      - name: Extract relevant logs using sed
        run: |
          # Extract log between the start and end patterns
          sed -n '/Scanning virtual machine image/,/Scan report:/p' log.txt > relevant_log.txt

      - name: Append relevant logs to job summary
        run: |
          echo "## Scan Results" >> $GITHUB_STEP_SUMMARY
          
          # Extract specific log fields
          image=$(sed -n 's/Scanning virtual machine image //p' relevant_log.txt)
          critical=$(sed -n 's/Vulnerable packages: CRITICAL: \([0-9]*\),.*/\1/p' relevant_log.txt)
          high=$(sed -n 's/Vulnerable packages:.*HIGH: \([0-9]*\),.*/\1/p' relevant_log.txt)
          medium=$(sed -n 's/Vulnerable packages:.*MEDIUM: \([0-9]*\),.*/\1/p' relevant_log.txt)
          low=$(sed -n 's/Vulnerable packages:.*LOW: \([0-9]*\).*/\1/p' relevant_log.txt)
          scan_report=$(sed -n 's/Scan report: //p' relevant_log.txt)
          
          # Create the markdown table with multiple columns
          echo "| Scanned Image | CRITICAL | HIGH | MEDIUM | LOW | Scan Report |" >> $GITHUB_STEP_SUMMARY
          echo "|---------------|----------|------|--------|-----|-------------|" >> $GITHUB_STEP_SUMMARY
          echo "| $image | $critical | $high | $medium | $low | [Link]($scan_report) |" >> $GITHUB_STEP_SUMMARY

