name: Demo

on:
  workflow_dispatch:

jobs:
  job-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a long log (Example)
        run: |
          echo "Generating a simulated log..."
          echo " __      _(_)____   ___| (_)" >> log.txt
          echo " \\ \\ /\\ / / |_ /  / __| | |" >> log.txt
          echo "  \\ V  V /| |/ / | (__| | |" >> log.txt
          echo "   \\_/\\_/|_/___|  \\___|_|_|" >> log.txt
          echo "Scanning virtual machine image ami-abcdef123456789" >> log.txt
          echo "Vulnerable packages: CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0" >> log.txt
          echo "Scan was successfully performed and no vulnerabilities were detected" >> log.txt
          echo "Scan report: https://app.wiz.io/findings/example/12312454" >> log.txt
          echo "This is the noisy part" >> log.txt
          for i in {1..10000}; do echo "Noise $i"; done >> log.txt

      - name: Extract and append relevant logs using awk
        run: |
          echo "## Scan Results" >> $GITHUB_STEP_SUMMARY
          
          # Use awk to extract and format fields as multiple rows
          awk '
            /Scanning virtual machine image/ { image=$NF }
            /Vulnerable packages:/ {
              match($0, /CRITICAL: ([0-9]+)/, critical_arr)
              match($0, /HIGH: ([0-9]+)/, high_arr)
              match($0, /MEDIUM: ([0-9]+)/, medium_arr)
              match($0, /LOW: ([0-9]+)/, low_arr)
              critical=critical_arr[1]
              high=high_arr[1]
              medium=medium_arr[1]
              low=low_arr[1]
            }
            /Scan report:/ { scan_report=$NF }
            END {
              printf "| Field            | Value                          |\n" >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "|------------------|-------------------------------|\n" >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| Scanned Image    | %s                             |\n", image >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| CRITICAL         | %s                             |\n", critical >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| HIGH             | %s                             |\n", high >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| MEDIUM           | %s                             |\n", medium >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| LOW              | %s                             |\n", low >> ENVIRON["GITHUB_STEP_SUMMARY"]
              printf "| Scan Report      | [Link](%s)                     |\n", scan_report >> ENVIRON["GITHUB_STEP_SUMMARY"]
            }
          ' log.txt
