name: Demo

on:
  workflow_dispatch:

jobs:
  job-summary:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a long log (Example)
        run: |
          echo "Generating a simulated log..."
          echo " __      _(_)____   ___| (_)" >> log.txt
          echo " \\ \\ /\\ / / |_ /  / __| | |" >> log.txt
          echo "  \\ V  V /| |/ / | (__| | |" >> log.txt
          echo "   \\_/\\_/|_/___|  \\___|_|_|" >> log.txt
          echo "Scanning virtual machine image ami-abcdef123456789" >> log.txt
          echo "Vulnerable packages: CRITICAL: 0, HIGH: 0, MEDIUM: 0, LOW: 0" >> log.txt
          echo "Scan was successfully performed and no vulnerabilities were detected" >> log.txt
          echo "Scan report: https://app.wiz.io/findings/example/12312454" >> log.txt
          echo "This is the noisy part" >> log.txt
          for i in {1..10000}; do echo "Noise $i"; done >> log.txt

      - name: Extract relevant logs using sed
        run: |
          # Extract log between the start and end patterns
          sed -n '/Scanning virtual machine image/,/Scan report:/p' log.txt > relevant_log.txt

      - name: Append relevant logs to job summary
        run: |
          echo "## Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat relevant_log.txt >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
